#+TITLE: Ruby on Rails Introduction
#+AUTHOR: Roberto
#+DATE: 2024-01-18
#+TAGS: ruby, rails, web-development, framework
#+OPTIONS: toc:nil num:nil

* What is Ruby on Rails?

Ruby on Rails, often shortened to Rails, is a web application framework written in Ruby. It follows the Model-View-Controller (MVC) pattern and emphasizes convention over configuration.

* Rails Philosophy

** Convention over Configuration
Rails makes assumptions about what you want to do and how you're going to do it, rather than requiring you to specify every little detail through configuration files.

** Don't Repeat Yourself (DRY)
Every piece of knowledge should have a single, unambiguous, authoritative representation within a system.

* MVC Architecture

** Model
- Represents the data and business logic
- Handles database interactions
- Located in app/models/

** View
- Handles the presentation layer
- Templates for HTML output
- Located in app/views/

** Controller
- Handles user input
- Coordinates between Model and View
- Located in app/controllers/

* Getting Started

** Installation
#+BEGIN_SRC bash
gem install rails
rails new myapp
cd myapp
rails server
#+END_SRC

** Generate a Controller
#+BEGIN_SRC bash
rails generate controller Welcome index
#+END_SRC

* Key Commands

- rails new: Create new Rails application
- rails server: Start development server
- rails generate: Generate code
- rails console: Open Rails console
- rails routes: Show all routes
